use_frameworks!

platform :ios, '8.0'

target 'KSDownloadManager_Example' do
  pod 'KSDownloadManager', :path => '../'

  target 'KSDownloadManager_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
